(define (problem problem-1)
    (:domain pyramid)
    (:objects
        D9 D5 DA C5 C3 S2 C9 D2 S7 C7 H5 SA - CARD
        DQ D4 CQ S8 D6 CJ D8 HJ C6 S4 H6 HX C8 C4 SQ - CARD
    )
    (:init
        (in-cycle1)

        (in-pyramid D9)
        (in-pyramid D5)
        (in-pyramid DA)
        (in-pyramid C5)
        (in-pyramid C3)
        (in-pyramid S2)
        (in-pyramid C9)
        (in-pyramid D2)
        (in-pyramid S7)
        (in-pyramid C7)
        (in-pyramid H5)
        (in-pyramid SA)

        (in-deck DQ)
        (in-deck D4)
        (in-deck CQ)
        (in-deck S8)
        (in-deck D6)
        (in-deck CJ)
        (in-deck D8)
        (in-deck HJ)
        (in-deck C6)
        (in-deck S4)
        (in-deck H6)
        (in-deck HX)
        (in-deck C8)
        (in-deck C4)
        (in-deck SQ)

        (sum-card-13 D9 D4)
        (sum-card-13 D9 S4)
        (sum-card-13 D9 C4)
        (sum-card-13 D5 S8)
        (sum-card-13 D5 D8)
        (sum-card-13 D5 C8)
        (sum-card-13 DA DQ)
        (sum-card-13 DA CQ)
        (sum-card-13 DA SQ)
        (sum-card-13 C5 S8)
        (sum-card-13 C5 D8)
        (sum-card-13 C5 C8)
        (sum-card-13 C3 HX)
        (sum-card-13 S2 CJ)
        (sum-card-13 S2 HJ)
        (sum-card-13 C9 D4)
        (sum-card-13 C9 S4)
        (sum-card-13 C9 C4)
        (sum-card-13 D2 CJ)
        (sum-card-13 D2 HJ)
        (sum-card-13 S7 D6)
        (sum-card-13 S7 C6)
        (sum-card-13 S7 H6)
        (sum-card-13 C7 D6)
        (sum-card-13 C7 C6)
        (sum-card-13 C7 H6)
        (sum-card-13 H5 S8)
        (sum-card-13 H5 D8)
        (sum-card-13 H5 C8)
        (sum-card-13 SA DQ)
        (sum-card-13 SA CQ)
        (sum-card-13 SA SQ)
        (sum-card-13 DQ DA)
        (sum-card-13 DQ SA)
        (sum-card-13 D4 D9)
        (sum-card-13 D4 C9)
        (sum-card-13 CQ DA)
        (sum-card-13 CQ SA)
        (sum-card-13 S8 D5)
        (sum-card-13 S8 C5)
        (sum-card-13 S8 H5)
        (sum-card-13 D6 S7)
        (sum-card-13 D6 C7)
        (sum-card-13 CJ S2)
        (sum-card-13 CJ D2)
        (sum-card-13 D8 D5)
        (sum-card-13 D8 C5)
        (sum-card-13 D8 H5)
        (sum-card-13 HJ S2)
        (sum-card-13 HJ D2)
        (sum-card-13 C6 S7)
        (sum-card-13 C6 C7)
        (sum-card-13 S4 D9)
        (sum-card-13 S4 C9)
        (sum-card-13 H6 S7)
        (sum-card-13 H6 C7)
        (sum-card-13 HX C3)
        (sum-card-13 C8 D5)
        (sum-card-13 C8 C5)
        (sum-card-13 C8 H5)
        (sum-card-13 C4 D9)
        (sum-card-13 C4 C9)
        (sum-card-13 SQ DA)
        (sum-card-13 SQ SA)

        (covers SA C7)
        (covers SA H5)
        (covers C7 D2)
        (covers C7 S7)
        (covers H5 S7)
        (covers C9 C5)
        (covers D2 C3)
        (covers D2 S2)
        (covers S7 S2)
        (covers C5 D5)
        (covers C3 D5)
        (covers C3 DA)
        (covers S2 DA)
        (covers D5 D9)
        (covers DA D9)

        (covers DQ D4)
        (covers D4 CQ)
        (covers CQ S8)
        (covers S8 D6)
        (covers D6 CJ)
        (covers CJ D8)
        (covers D8 HJ)
        (covers HJ C6)
        (covers C6 S4)
        (covers S4 H6)
        (covers H6 HX)
        (covers HX C8)
        (covers C8 C4)
        (covers C4 SQ)
    )
    (:goal
        (empty-pyramid)
    )
)
