(define (problem problem-2)
    (:domain pyramid)
    (:objects
        S5 DJ D6 D3 C6 H3 C8 D4 HK H6 C3 C4 HJ D2 S6 DQ H2 SK CQ S2 H4 HQ CK C5 S8 CJ S4 SQ - CARD
        SA CA D8 H5 D5 HX HA C2 D9 C9 C7 DK H9 S7 CX D7 S3 SJ DA DX S9 H7 SX H8 - CARD
    )
    (:init
        (in-cycle1)

        (in-pyramid S5)
        (in-pyramid DJ)
        (in-pyramid D6)
        (in-pyramid D3)
        (in-pyramid C6)
        (in-pyramid H3)
        (in-pyramid C8)
        (in-pyramid D4)
        (in-pyramid HK)
        (in-pyramid H6)
        (in-pyramid C3)
        (in-pyramid C4)
        (in-pyramid HJ)
        (in-pyramid D2)
        (in-pyramid S6)
        (in-pyramid DQ)
        (in-pyramid H2)
        (in-pyramid SK)
        (in-pyramid CQ)
        (in-pyramid S2)
        (in-pyramid H4)
        (in-pyramid HQ)
        (in-pyramid CK)
        (in-pyramid C5)
        (in-pyramid S8)
        (in-pyramid CJ)
        (in-pyramid S4)
        (in-pyramid SQ)

        (in-deck SA)
        (in-deck CA)
        (in-deck D8)
        (in-deck H5)
        (in-deck D5)
        (in-deck HX)
        (in-deck HA)
        (in-deck C2)
        (in-deck D9)
        (in-deck C9)
        (in-deck C7)
        (in-deck DK)
        (in-deck H9)
        (in-deck S7)
        (in-deck CX)
        (in-deck D7)
        (in-deck S3)
        (in-deck SJ)
        (in-deck DA)
        (in-deck DX)
        (in-deck S9)
        (in-deck H7)
        (in-deck SX)
        (in-deck H8)

        (sum-card-13 S5 C8)
        (sum-card-13 S5 S8)
        (sum-card-13 S5 D8)
        (sum-card-13 S5 H8)
        (sum-card-13 DJ D2)
        (sum-card-13 DJ H2)
        (sum-card-13 DJ S2)
        (sum-card-13 DJ C2)
        (sum-card-13 D6 C7)
        (sum-card-13 D6 S7)
        (sum-card-13 D6 D7)
        (sum-card-13 D6 H7)
        (sum-card-13 D3 HX)
        (sum-card-13 D3 CX)
        (sum-card-13 D3 DX)
        (sum-card-13 D3 SX)
        (sum-card-13 C6 C7)
        (sum-card-13 C6 S7)
        (sum-card-13 C6 D7)
        (sum-card-13 C6 H7)
        (sum-card-13 H3 HX)
        (sum-card-13 H3 CX)
        (sum-card-13 H3 DX)
        (sum-card-13 H3 SX)
        (sum-card-13 C8 S5)
        (sum-card-13 C8 C5)
        (sum-card-13 C8 H5)
        (sum-card-13 C8 D5)
        (sum-card-13 D4 D9)
        (sum-card-13 D4 C9)
        (sum-card-13 D4 H9)
        (sum-card-13 D4 S9)
        (king HK)
        (sum-card-13 H6 C7)
        (sum-card-13 H6 S7)
        (sum-card-13 H6 D7)
        (sum-card-13 H6 H7)
        (sum-card-13 C3 HX)
        (sum-card-13 C3 CX)
        (sum-card-13 C3 DX)
        (sum-card-13 C3 SX)
        (sum-card-13 C4 D9)
        (sum-card-13 C4 C9)
        (sum-card-13 C4 H9)
        (sum-card-13 C4 S9)
        (sum-card-13 HJ D2)
        (sum-card-13 HJ H2)
        (sum-card-13 HJ S2)
        (sum-card-13 HJ C2)
        (sum-card-13 D2 DJ)
        (sum-card-13 D2 HJ)
        (sum-card-13 D2 CJ)
        (sum-card-13 D2 SJ)
        (sum-card-13 S6 C7)
        (sum-card-13 S6 S7)
        (sum-card-13 S6 D7)
        (sum-card-13 S6 H7)
        (sum-card-13 DQ SA)
        (sum-card-13 DQ CA)
        (sum-card-13 DQ HA)
        (sum-card-13 DQ DA)
        (sum-card-13 H2 DJ)
        (sum-card-13 H2 HJ)
        (sum-card-13 H2 CJ)
        (sum-card-13 H2 SJ)
        (king SK)
        (sum-card-13 CQ SA)
        (sum-card-13 CQ CA)
        (sum-card-13 CQ HA)
        (sum-card-13 CQ DA)
        (sum-card-13 S2 DJ)
        (sum-card-13 S2 HJ)
        (sum-card-13 S2 CJ)
        (sum-card-13 S2 SJ)
        (sum-card-13 H4 D9)
        (sum-card-13 H4 C9)
        (sum-card-13 H4 H9)
        (sum-card-13 H4 S9)
        (sum-card-13 HQ SA)
        (sum-card-13 HQ CA)
        (sum-card-13 HQ HA)
        (sum-card-13 HQ DA)
        (king CK)
        (sum-card-13 C5 C8)
        (sum-card-13 C5 S8)
        (sum-card-13 C5 D8)
        (sum-card-13 C5 H8)
        (sum-card-13 S8 S5)
        (sum-card-13 S8 C5)
        (sum-card-13 S8 H5)
        (sum-card-13 S8 D5)
        (sum-card-13 CJ D2)
        (sum-card-13 CJ H2)
        (sum-card-13 CJ S2)
        (sum-card-13 CJ C2)
        (sum-card-13 S4 D9)
        (sum-card-13 S4 C9)
        (sum-card-13 S4 H9)
        (sum-card-13 S4 S9)
        (sum-card-13 SQ SA)
        (sum-card-13 SQ CA)
        (sum-card-13 SQ HA)
        (sum-card-13 SQ DA)
        (sum-card-13 SA DQ)
        (sum-card-13 SA CQ)
        (sum-card-13 SA HQ)
        (sum-card-13 SA SQ)
        (sum-card-13 CA DQ)
        (sum-card-13 CA CQ)
        (sum-card-13 CA HQ)
        (sum-card-13 CA SQ)
        (sum-card-13 D8 S5)
        (sum-card-13 D8 C5)
        (sum-card-13 D8 H5)
        (sum-card-13 D8 D5)
        (sum-card-13 H5 C8)
        (sum-card-13 H5 S8)
        (sum-card-13 H5 D8)
        (sum-card-13 H5 H8)
        (sum-card-13 D5 C8)
        (sum-card-13 D5 S8)
        (sum-card-13 D5 D8)
        (sum-card-13 D5 H8)
        (sum-card-13 HX D3)
        (sum-card-13 HX H3)
        (sum-card-13 HX C3)
        (sum-card-13 HX S3)
        (sum-card-13 HA DQ)
        (sum-card-13 HA CQ)
        (sum-card-13 HA HQ)
        (sum-card-13 HA SQ)
        (sum-card-13 C2 DJ)
        (sum-card-13 C2 HJ)
        (sum-card-13 C2 CJ)
        (sum-card-13 C2 SJ)
        (sum-card-13 D9 D4)
        (sum-card-13 D9 C4)
        (sum-card-13 D9 H4)
        (sum-card-13 D9 S4)
        (sum-card-13 C9 D4)
        (sum-card-13 C9 C4)
        (sum-card-13 C9 H4)
        (sum-card-13 C9 S4)
        (sum-card-13 C7 D6)
        (sum-card-13 C7 C6)
        (sum-card-13 C7 H6)
        (sum-card-13 C7 S6)
        (king DK)
        (sum-card-13 H9 D4)
        (sum-card-13 H9 C4)
        (sum-card-13 H9 H4)
        (sum-card-13 H9 S4)
        (sum-card-13 S7 D6)
        (sum-card-13 S7 C6)
        (sum-card-13 S7 H6)
        (sum-card-13 S7 S6)
        (sum-card-13 CX D3)
        (sum-card-13 CX H3)
        (sum-card-13 CX C3)
        (sum-card-13 CX S3)
        (sum-card-13 D7 D6)
        (sum-card-13 D7 C6)
        (sum-card-13 D7 H6)
        (sum-card-13 D7 S6)
        (sum-card-13 S3 HX)
        (sum-card-13 S3 CX)
        (sum-card-13 S3 DX)
        (sum-card-13 S3 SX)
        (sum-card-13 SJ D2)
        (sum-card-13 SJ H2)
        (sum-card-13 SJ S2)
        (sum-card-13 SJ C2)
        (sum-card-13 DA DQ)
        (sum-card-13 DA CQ)
        (sum-card-13 DA HQ)
        (sum-card-13 DA SQ)
        (sum-card-13 DX D3)
        (sum-card-13 DX H3)
        (sum-card-13 DX C3)
        (sum-card-13 DX S3)
        (sum-card-13 S9 D4)
        (sum-card-13 S9 C4)
        (sum-card-13 S9 H4)
        (sum-card-13 S9 S4)
        (sum-card-13 H7 D6)
        (sum-card-13 H7 C6)
        (sum-card-13 H7 H6)
        (sum-card-13 H7 S6)
        (sum-card-13 SX D3)
        (sum-card-13 SX H3)
        (sum-card-13 SX C3)
        (sum-card-13 SX S3)
        (sum-card-13 H8 S5)
        (sum-card-13 H8 C5)
        (sum-card-13 H8 H5)
        (sum-card-13 H8 D5)

        (covers HQ DQ)
        (covers CK DQ)
        (covers CK H2)
        (covers C5 H2)
        (covers C5 SK)
        (covers S8 SK)
        (covers S8 CQ)
        (covers CJ CQ)
        (covers CJ S2)
        (covers S4 S2)
        (covers S4 H4)
        (covers SQ H4)
        (covers DQ C3)
        (covers H2 C3)
        (covers H2 C4)
        (covers SK C4)
        (covers SK HJ)
        (covers CQ HJ)
        (covers CQ D2)
        (covers S2 D2)
        (covers S2 S6)
        (covers H4 S6)
        (covers C3 C8)
        (covers C4 C8)
        (covers C4 D4)
        (covers HJ D4)
        (covers HJ HK)
        (covers D2 HK)
        (covers D2 H6)
        (covers S6 H6)
        (covers C8 D3)
        (covers D4 D3)
        (covers D4 C6)
        (covers HK C6)
        (covers HK H3)
        (covers H6 H3)
        (covers D3 DJ)
        (covers C6 DJ)
        (covers C6 D6)
        (covers H3 D6)
        (covers DJ S5)
        (covers D6 S5)

        (covers SA CA)
        (covers CA D8)
        (covers D8 H5)
        (covers H5 D5)
        (covers D5 HX)
        (covers HX HA)
        (covers HA C2)
        (covers C2 D9)
        (covers D9 C9)
        (covers C9 C7)
        (covers C7 DK)
        (covers DK H9)
        (covers H9 S7)
        (covers S7 CX)
        (covers CX D7)
        (covers D7 S3)
        (covers S3 SJ)
        (covers SJ DA)
        (covers DA DX)
        (covers DX S9)
        (covers S9 H7)
        (covers H7 SX)
        (covers SX H8)
    )
    (:goal
        (empty-pyramid)
    )
)
